---
- name: Remove APT packages we do not want
  apt:
    name:
      # Manually installing the DPKG package is annoying, use the Snap version.
      - discord
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  become: yes

- name: Add Chrome signing key
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    id: EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796
  become: yes

- name: Add Google Chrome APT repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
  become: yes

- name: Add Git PPA to get autoSetupRemote support
  apt_repository:
    repo: 'ppa:git-core/ppa'
  become: yes

- name: Add Git PPA GPG key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: E1DD270288B4E6030699E45FA1715D88E1DF1F24
    keyring: /etc/apt/trusted.gpg.d/git.gpg
  become: yes

- name: Add DDEV signing key
  ansible.builtin.apt_key:
    url: https://apt.fury.io/drud/gpg.key
    id: DBD730A3A581BDAC98BAF17FC16711FC1179C7CA
    keyring: /etc/apt/trusted.gpg.d/ddev.gpg
  become: yes

- name: Add DDEV APT repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://apt.fury.io/drud/ * *
    state: present
    filename: ddev
  become: yes

- name: Add GCP CLI signing key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  become: yes

- name: Add GCP CLI APT repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.cloud.google.com/apt cloud-sdk main
    state: present
    filename: gcp-cli
  become: yes

- name: Add Docker signing key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
  become: yes

- name: Add Docker APT repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable
    state: present
    filename: docker
  become: yes

- name: Add Lens signing key
  ansible.builtin.apt_key:
    url: https://downloads.k8slens.dev/keys/gpg
    keyring: /etc/apt/trusted.gpg.d/lens.gpg
  become: yes

- name: Add Lens APT repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/lens.gpg] https://downloads.k8slens.dev/apt/debian stable main
    state: present
    filename: lens
  become: yes

- name: Install Ubuntu packages we want
  apt:
    name:
      # Used for automatic background updates, see
      # https://klau.si/blog/fully-hidden-automatic-system-updates-ubuntu/
      - anacron
      - apt-transport-https
      - build-essential
      - curl
      - ddev
      - g++
      - gcc
      # For GNOME system monitor shell extension.
      - gir1.2-gtop-2.0
      - gir1.2-nm-1.0
      - gir1.2-clutter-1.0
      - git
      - gnome-shell-extensions
      - gnome-system-monitor
      - google-chrome-stable
      - google-cloud-sdk
      - google-cloud-sdk-gke-gcloud-auth-plugin
      - htop
      - libreoffice-calc
      - libreoffice-gtk3
      - libreoffice-writer
      - libssl-dev
      - make
      - net-tools
      - p7zip-full
      - pwgen
      - python-is-python3
      # Required for dconf ansible tasks we use.
      - python3-psutil
      - qbittorrent
      - ripgrep
      - tilda
      - ttf-mscorefonts-installer
      - ubuntu-restricted-extras
      - unison-gtk
      - vim
      - vlc
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - wget
      - gnome-tweaks
      - lsb-release
      - ca-certificates
      - gnupg
      - lens
      - zsh
      - blueman
    state: present
    update_cache: true
  become: yes

- name: Install Docker compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  become: true