---
- name: Remove Snap packages we do not want
  community.general.snap:
    name:
      # Firefox via Snap is super slow on cold starts, install the APT
      # version below instead.
      - firefox
      # The APT version of LibreOffice ist faster and works with my extensions
      # again.
      - libreoffice
      # We don't need the graphical snap store and it makes problems with
      # auto-updating snaps.
      - snap-store
    state: absent
  become: yes

- name: Install Snap packages we want
  community.general.snap:
    name:
      - yq
      - zoom-client
      - kubectl
      - helm
  become: yes

- name: Install Snap packages in classic mode that we want
  community.general.snap:
    name:
      - code
    classic: yes
  become: yes

- name: Put auto APT script into place for Anacron
  ansible.builtin.copy:
    src: autoapt.sh
    dest: /etc/cron.daily/autoapt
    mode: preserve
  become: yes

- name: Ensure .local/bin directory exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes
  become: yes

- name: Remove Canonical spam advertisements in APT output
  ansible.builtin.copy:
    content: ""
    dest: /etc/apt/apt.conf.d/20apt-esm-hook.conf
  become: yes

- name: Show raw system output on Ubuntu startup instead of splash screen
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
  become: yes
  register: grub_splash

- name: Update GRUB if needed
  shell: update-grub
  become: yes
  when: grub_splash.changed
